receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: "otelcol"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
