services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      - "5678:5678"  # Main app debugging
      - "5679:5679"  # Test debugging (only used when DEBUG_TESTS=true)
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./monitoring/otel-collector/otel-collector-config.yml:/etc/otelcol/config.yml
    ports:
      - "4319:4317"   # OTLP gRPC receiver (avoid conflict with tempo)
      - "4318:4318"   # OTLP HTTP receiver
      - "9464:9464"   # Prometheus metrics exporter
    command: ["--config", "/etc/otelcol/config.yml"]
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus

  dev-oidc:
    build: ./auth/dev-oidc
    container_name: dev-oidc
    ports:
      - "8088:8088"
    environment:
      - OIDC_ISSUER=http://dev-oidc:8088
      - OIDC_REDIRECT_URI=http://frontend:3000/callback
    depends_on:
      - backend


  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317:4317"   # OTLP gRPC receiver
    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo/tempo.yml
    command: ["-config.file=/etc/tempo/tempo.yml"]

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"   # Loki HTTP API
    volumes:
      - ./monitoring/loki/loki.yml:/etc/loki/loki.yml
    command: ["-config.file=/etc/loki/loki.yml"]

volumes:
  pgdata:
  pgdata_test:
