services:
  # Reverse proxy and dashboard
  nginx:
    build: ./nginx
    ports:
      - "1111:80"  # Main entry point
    depends_on:
      - frontend
      - backend
      - pgadmin
      - grafana
      - prometheus

  frontend:
    build: ./frontend
    # Remove external port mapping - access through nginx
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_BASE_URL=/api  # Now relative to nginx proxy
      - WDS_SOCKET_PORT=1111  # WebSocket through nginx
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    # Remove external port mapping - access through nginx
    # Keep debug ports for development
    ports:
      - "5678:5678"  # Main app debugging
      - "5679:5679"  # Test debugging (only used when DEBUG_TESTS=true)
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_X_FRAME_OPTIONS: "'ALLOWALL'"
    # Remove external port mapping - access through nginx
    depends_on:
      - db
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./monitoring/otel-collector/otel-collector-config.yml:/etc/otelcol/config.yml
    ports:
      - "4319:4317"   # OTLP gRPC receiver (avoid conflict with tempo)
      - "4318:4318"   # OTLP HTTP receiver
      - "9464:9464"   # Prometheus metrics exporter
    command: ["--config", "/etc/otelcol/config.yml"]
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:1111/prometheus/'
      - '--web.route-prefix=/prometheus/'
    # Remove external port mapping - access through nginx
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # Remove external port mapping - access through nginx
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SERVER_ROOT_URL=http://localhost:1111/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus


  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317:4317"   # OTLP gRPC receiver
    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo/tempo.yml
    command: ["-config.file=/etc/tempo/tempo.yml"]

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"   # Loki HTTP API
    volumes:
      - ./monitoring/loki/loki.yml:/etc/loki/loki.yml
    command: ["-config.file=/etc/loki/loki.yml"]

volumes:
  pgdata:
  pgdata_test:
