services:
  migrate:
    build: ./backend
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/app
    networks:
      - react-fastapi-postgres_default

networks:
  react-fastapi-postgres_default:
    external: true
