"""Change finalized field to locked in notes table

Revision ID: 8caf0a8eaa64
Revises: bc155b33fec1
Create Date: 2025-07-05 01:52:54.272194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caf0a8eaa64'
down_revision: Union[str, Sequence[str], None] = 'bc155b33fec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'finalized', new_column_name='locked')
    op.drop_index(op.f('ix_examples_id'), table_name='notes')
    op.drop_index(op.f('ix_examples_uuid'), table_name='notes')
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_uuid'), 'notes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'locked', new_column_name='finalized')
    op.drop_index(op.f('ix_notes_uuid'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.create_index(op.f('ix_examples_uuid'), 'notes', ['uuid'], unique=True)
    op.create_index(op.f('ix_examples_id'), 'notes', ['id'], unique=False)
    # ### end Alembic commands ###
